### ISSUE TITLE
Not Work On Windows 10 64Bit

### ISSUE THREAD

**Issue by d4rks0ul555** [bertugerkaya/keylogger#1]
how to making the payloads works in windows 10 64bit, thanks

**Comment by d4rks0ul555** [comment]
i mean the keylogger

**Comment by bertugerkaya** [comment]
Hello,

If you have any trouble with that keylogger, it's all about the script, because it's old. You can edit all of it or you can replace with another script. This will solve your problem. I suggest you to replace with another one because there is more effective scripts  on the internet more then this one.

Best regards.

**Comment by d4rks0ul555** [comment]
thanks for your info
